apiVersion: v1
kind: ServiceAccount
metadata:
  name: opensphere-plugin-postgres
  namespace: opensphere-system
  labels:
    app.kubernetes.io/name: opensphere-plugin-postgres
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: opensphere-plugin-postgres-runtime
  namespace: opensphere-system
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opensphere-plugin-postgres-runtime
  namespace: opensphere-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: opensphere-plugin-postgres-runtime
subjects:
  - kind: ServiceAccount
    name: opensphere-plugin-postgres
    namespace: opensphere-system
